# config/app.yml for rails-settings-cached
defaults: &defaults
  site_title: Scifi
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  open_registrations: true
  open_deletion: true
  timeline_preview: false
  default_sensitive: false
  unfollow_modal: true
  closed_registrations_message: 'Closed for now -- check in with @chris@scifi.fyi'
  boost_modal: true
  delete_modal: true
  auto_play_gif: false
  reduce_motion: false
  system_font_ui: false
  noindex: false
  theme: 'default'
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: true
  interactions:
    must_be_follower: false
    must_be_following: false
    must_be_following_dm: false
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
  bootstrap_timeline_accounts: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
